### ISSUE TITLE
Null pointer exception during call to resourceList

### ISSUE THREAD

**Issue by kiruba3441** [wkennedy/swagger4spring-web#71]
Hi,

When i include @Api annotation atop a @Controller annotation i get the above mentioned null pointer exception.

using: 0.3.0 version
spring: 3.2.8
java: 1.6
usage:
@Api(value = "list abc devices",consumes="",description="Operations related to abc devices")
@Controller
public class AbcController {
}

Exception:

May 20, 2014 12:14:36 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [glass] in context with path [/glass] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException
    at com.knappsack.swagger4springweb.parser.SpringMVCApiReader$class.readRecursive(SpringMVCApiReader.scala:231)
    at com.knappsack.swagger4springweb.parser.SpringApiReader.readRecursive(SpringApiReader.scala:12)
    at com.knappsack.swagger4springweb.parser.SpringMVCApiReader$class.read(SpringMVCApiReader.scala:216)
    at com.knappsack.swagger4springweb.parser.SpringApiReader.read(SpringApiReader.scala:12)
    at com.knappsack.swagger4springweb.parser.ApiParserImpl.processControllerApi(ApiParserImpl.java:147)
    at com.knappsack.swagger4springweb.parser.ApiParserImpl.processControllers(ApiParserImpl.java:104)
    at com.knappsack.swagger4springweb.parser.ApiParserImpl.createApiListings(ApiParserImpl.java:89)
    at com.knappsack.swagger4springweb.controller.ApiDocumentationController.getDocs(ApiDocumentationController.java:158)
    at com.knappsack.swagger4springweb.controller.ApiDocumentationController.getResourceList(ApiDocumentationController.java:172)
    at com.knappsack.swagger4springweb.controller.ApiDocumentationController.getResources(ApiDocumentationController.java:42)
java.lang.NullPointerException
    at com.knappsack.swagger4springweb.parser.SpringMVCApiReader$class.readRecursive(SpringMVCApiReader.scala:231)

**Comment by ankit-akosha** [comment]
I am still getting this error.
java.lang.NullPointerException
	com.knappsack.swagger4springweb.parser.SpringMVCApiReader$class.readRecursive(SpringMVCApiReader.scala:268)
	com.knappsack.swagger4springweb.parser.SpringApiReader.readRecursive(SpringApiReader.scala:13)
	com.knappsack.swagger4springweb.parser.SpringMVCApiReader$class.read(SpringMVCApiReader.scala:233)
	com.knappsack.swagger4springweb.parser.SpringApiReader.read(SpringApiReader.scala:13)
	com.knappsack.swagger4springweb.parser.ApiParserImpl.processControllerApi(ApiParserImpl.java:174)
	com.knappsack.swagger4springweb.parser.ApiParserImpl.processControllers(ApiParserImpl.java:123)
	com.knappsack.swagger4springweb.parser.ApiParserImpl.createApiListings(ApiParserImpl.java:112)
	com.knappsack.swagger4springweb.controller.ApiDocumentationController.getDocs(ApiDocumentationController.java:104)
	com.knappsack.swagger4springweb.controller.ApiDocumentationController.getResourceList(ApiDocumentationController.java:118)
	com.knappsack.swagger4springweb.controller.ApiDocumentationController.getResources(ApiDocumentationController.java:52)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by ankit-akosha** [comment]
Spring Version :- 4.1.4-RELEASE
swagger4spring-web : 0.3.5
Java : 1.8
